name: Run Playwright Tests

on: [push, pull_request]  # Ejecutar en cada push o PR

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3  # Clonar el repositorio

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Usar Node.js 18

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install

      - name: Run Playwright Tests
        run: npx playwright test

      - name: Upload Playwright Report
        uses: actions/upload-artifact@v3
        with:
          name: Playwright Report
          path: playwright-report
